#!/bin/bash

wid=$1
class=$2
instance=$3
consequences=$4
case "$class" in
discord)
	echo "desktop='IV' follow=on"
	;;
Screenkey)
	echo "manage=off"
	;;
spotify)
	echo "desktop='V' state=tiled"
	;;
Zathura)
	echo "state=tiled"
	;;
esac
