#!/usr/bin/sh
#Disable touchscreen
id=$(xinput list  | grep 'Touchscreen' | awk '{print $5}' | cut -b 4-6)
for i in ${id[@]};
do
  xinput disable $i
done
sxhkd &
#-----------------------------------
bspc monitor -d I II III IV V
#-----------------------------------
bspc config pointer_modifier mod1
bspc config border_width 2
bspc config window_gap 2
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
#-----------------------------------
bspc config external_rules_command "$HOME/.config/bspwm/bspwm-external-rules"
bspc config pointer_follows_focus true 
feh --bg-fill $HOME/Pictures/wallpaper.jpg
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
picom &
